services:
  urlita:
    restart: always
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://database:5432/${DATABASE_NAME}"
      DB_USER: "${DATABASE_USER}"
      DB_PASSWORD: "${DATABASE_PASSWORD}"
    depends_on:
      - database
  database:
    image: 'postgres:18'
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
 